Changes made to monitoring track changes, should fix https://github.com/JourneyDocker/Plex-Auto-Languages/issues/1 As well as improved track monitoring
Also fixed an issue for items missing time stamps:
Traceback (most recent call last):
  File "/app/plex_auto_languages/plex_alert_handler.py", line 66, in _process_alerts
    alert.process(self._plex)
    ~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/app/plex_auto_languages/alerts/timeline.py", line 62, in process
    if item.addedAt < datetime.now() - timedelta(minutes=5):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'NoneType' and 'datetime.datetime'